### ISSUE TITLE
Name length dependent registration price

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#108]
Proposal is as an increasing account creation fee dependent on the account name length.

Related to #62

**Comment by Nemo1369** [comment]
@21xhipster Does the proposal means the new account balance would contain the whole creation fee?

**Comment by 21xhipster** [comment]
![screen shot 2017-05-07 at 19 40 10](https://cloud.githubusercontent.com/assets/410789/25783476/0c523dd6-335d-11e7-9165-f5ffc4fc8b5e.png)

**Comment by 21xhipster** [comment]
@Nemo1369 I would say that account should receive basic fee (5 Golos), Others should go to `null` account (to be burned)

**Comment by serejandmyself** [comment]
Why should other tokens be burned if we are in a "for profit" model? Why not use these tokens to fund @golos or to be more exact Golos Core. Its a hefty add on to the budget VS. a not so obvious plus of "a minus" to the infaltion

**Comment by serejandmyself** [comment]
Also i dont see what is your logic behind the pricing model of the names. We need to apply a similar logic to UIA creation (both token placment and funding)

**Comment by serejandmyself** [comment]
@Nemo1369 is this done for UIA?

**Comment by Nemo1369** [comment]
The name cost distribution curve proposal is: producer_reward_per_block * blocks_per_day * 90 / (name.size() - minimum_asset_symbol_length + 1) ^ 3

**Comment by Nemo1369** [comment]
Closed with 9d0304f144

**Comment by On1x** [comment]
I'm against user login fees.

**Comment by serejandmyself** [comment]
I think that logins should still cost. Otherwise we will have a problem with namehoarding at the very least. In any case, i propose to use different numbers. More realistic. It is implemnet and works fine in bts. Also please note that the fee goes towards the network. That meaning that everyone is in a win-win situation. I would even propose a future choice for witnesses to make a choise of wether to burn this fee, or leave it as a paymnet for their oen work. Or split it accordingly

**Comment by serejandmyself** [comment]
@On1x Please make propostions. If its to take it off. Please provide the reason you wish to do so. Smily faces dont help much

**Comment by gropox** [comment]
Yes, nobody of active witnesses asked this feature.   I'm against fee for user names. Implement it without discussing that is bad. Are you sure that this a good idea is. What if you are wrong?

It shall be disabled in coming HF and discussed with community.

**Comment by Nemo1369** [comment]
Reopened according to the name cost necessity discussion

**Comment by litrbooh** [comment]
Коллеги, извините, что я с вами по-русски. На албанском и английском не умею.

Но! У нас проблема в том, регистрация стоит денег. И надо делать её бесплатной за счет делегирования, или делать стимулы для регистрантов за счет введения реферальных выблат. А вы хотите только увеличить стоимость регистрации? Нафига козе баян?

**Comment by litrbooh** [comment]
Мы же про имена юхзеров говорим, да? Цена на имена для токенов - остается.

**Comment by gropox** [comment]
В сети bitshares регистратор получает часть комиссионных с пользователей, которых он зарегистрировал, там ему выгодно регистрировать пользователей. На голосе этого нет. Зачем ставить препоны регистратору.

С другой стороны, если я правильно понял, от 8 знаков, не надо платить комиссионные за имя. Возможно тогда это и не так страшно, как кажется, возможно даже и хорошо для блокчейна, если токены будут сжигать. Но все равно, внедрять это без обсуждения не очень хорошая идея. 

Было бы не плохо написать пост об этом. Написать, что сулят комиссионные, какие ограничения получит регистратор, как вычисляются комиссионные. Если сильных возражений не поступит и если никто не найдет подводных камней, то можно и оставить.

**Comment by VIM-Arcange** [comment]
New user registration has already a cost, and is paid either by "the platform" (i.e. golos.io) or by the registrar.
I do not understand why the price should be variable depending on the name length.
Please stop adding new features in the forthcoming HF!

**Comment by Nemo1369** [comment]
@VIM-Arcange It is not really a new feature. The discussion, as far as you see, have started long time ago. It is about getting witnesses involved in the developing process.

**Comment by VIM-Arcange** [comment]
> The discussion, as far as you see, have started long time ago

@Nemo1369 From my point of view, the **real** discussion has only started a few hours ago.
This proposal has never been submitted widely to the community. Not all witnesses are developpers and therefore not all witnesses are aware new proposals made on github.
I think golos.core dev team should really consider something else or something complementary to github as a channel of communication if they want to involve **all** witnesses.

**Comment by serejandmyself** [comment]
@all I think it is ridiculous to propose any other channels for development discussions apart from github. All other communication channels are for feedback, not for development discussions. It is also a bit ridiculous to hear that not ALL witnesses have github. That’s very strange to hear... Why are those people witnesses? Why would you vote for someone who doesn’t read the code? I think you’re missing the point of what a witness job is in its essence.

Never the less. Let’s discuss the issue. @Nemo1369 I propose to take this off and leave it only for UIA as was proposed by the witnesses originally in our slack.

For future reference. We have made tons of announcements that ALL features will be discussed via github (that doesn’t mean we will not double it to our blogs. But main technical disscuisions will be held here guys).

**Comment by gropox** [comment]
@serejandmyself but you could anounce features you plan to integrate. It is not effective if witnesses will poll the github for new stuff and filter bugfixes, features and so on. Either some Issues are dfescribed very cryptical. Without any usefull description.

**Comment by serejandmyself** [comment]
@gropox I think regardless of announcements (which were missing for this feature, you are right). Witnesses MUST poll github for that. 

In order to make life easier, there are milestones. I.E. right now this is HF 0.2. IF you press milestones 0.2 in issues, you will filter the issues and their work progress accordingly. 

For example, here is the milestone list (proposed by our team and not yet discussed, as it is stupid to discuss anything before this HF is finished first), for HF 0.3:

https://github.com/GolosChain/golos/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.3.0

**Comment by VIM-Arcange** [comment]
@serejandmyself 
>Why would you vote for someone who doesn’t read the code?

Because this someone is doing great job at promoting the platform. 
For me, witnesses have 3 roles: technical, financial and social. And they do not need to master perfectly each of these 3 roles. I don't believe any of the current witnesse do.

Do you personally read and understand every single line of the code?

**Comment by serejandmyself** [comment]
@VIM-Arcange To answer your question first: Of course not. 
If i don't I tend to find the right people for me to help me to understand what is in the code. Otherwise I will not be involved with the project financially in any case. 
As I am an investor into this project, I have done my homework. And will keep on doing it, in regardless to my status on this project, as far as I have a penny invested.

I do not think it is possible for a witness to have more than 1 single role. 
That is: technical. That’s why the network decides to pay them.

Social? Well, anyone involved. I.e. investor, witness, active user, hired worker, should (if not must in case of a hired worker), be doing the social work and promotion.

I don’t think witnesses are obliged to sponsor anything at all. If they do, great. Their main job is to keep the network running.

Back to our subject: (let's stay on it please). @Nemo1369 ?

**Comment by Nemo1369** [comment]
Account name registration fee removed with 428e8d6
