### ISSUE TITLE
Automatic witness downvoting

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/golos#111]

**Comment by Nemo1369** [comment]
Duplicates #99

**Comment by 21xhipster** [comment]
Guys. Would love to get some info on the state of the issue. A lot happens since the issue first arise and now people want this ...

**Comment by serejandmyself** [comment]
@Nemo1369 @kotbegemot This should be implemented in the coming HF, as agreed!

**Comment by litrbooh** [comment]
А тут можно по-русски? Было ещё пожелание, сделать уведомление для пользователей о сбросе из голосов. Но, конечно, важнее реализовать сброс  и без уведомлений, если с ними проблемы.

**Comment by 0n0t0le** [comment]
+ Confirmed, would like get it in current HF

**Comment by serejandmyself** [comment]
@litrbooh Вопрос о реализации UI лучше адресовать командам веб клиентов. Например голос ио, голд войс и тд

**Comment by On1x** [comment]
@litrbooh я согласен с @serejandmyself - это дело всецело клиентов которые имеют свою систему уведомлений. Со своей стороны постараюсь внедрить уведомления юзеров.

**Comment by VIM-Arcange** [comment]
Delegate's vote removal should not be implemented without discussing how the process will work.
On1x shared a very interesting document from Bitshares, with many interesting "issues" this process generates.
- How will users be notified of the vote removal?
- How will delegate be notified of the vote removal?
- When vote removal will occurs (especially after enabling the process)? Will all first vote removal occurs at the same time?
- What about accounts who proxies their vote?

This should be discussed, or at least clarified, before starting development!

**Comment by On1x** [comment]
@VIM-Arcange it's talks in past, about notify. Does anyone have notifies in current state? No. It can be developed like plugin or 3rd party app. We don't need notify for it. Because living without them all the time.
About logically for unvote - i preffer just write witness_vote timestamp and when witness scheldule work use unvote for votes lesser that current timestamp sub 90 days*24hours*60sec.
Or make queue for expired operations, like change_recovery:
https://github.com/GolosChain/golos/blob/master/libraries/chain/steem_evaluator.cpp#L1735
executed there:
https://github.com/GolosChain/golos/blob/master/libraries/chain/database.cpp#L2171

**Comment by serejandmyself** [comment]
@VIM-Arcange The feature has been discussed and requested by the community enough times to implement this. 
As for notifications on UI level, this is a question for any client out there like golos.io or goldvoice etc.

**Comment by VIM-Arcange** [comment]
@serejandmyself My concern is less about notification than the removal process itself.
What will happens when delegate votes from the biggest whale(s) will expire? 
Because ones often vote for several delegates at the same time, I guess you will suddenly have a bunch of top-19 falling out of it.
Have you considered such cases in terms of network security?

**Comment by Nemo1369** [comment]
@VIM-Arcange The downvoting is not about removing all the votes, it means every single vote will expire after some time. So that means the community should become more politically active. Maybe the implementation of a lower limit of non-expirable votes would be fine? I mean let us all the votes for witnesses have expired, except latest 19. Let us make them unexpirable until any other user voted for some witness.

**Comment by Nemo1369** [comment]
Witness votes now have a 3 month age upper limit. Just after witness vote gets expired, virtual operation ```expire_witness_vote_operation``` gets pushed. Implementation proposal is contained in feac99edec.

**Comment by roelandp** [comment]
this will most probably be not a good thing for the network. asking people to vote every x times will just not work. Why would you demand from your users to do this over and over again. Most probably a couple whales / witnesses will run re-voting scripts. After 3 months the network will be taken over if no good safe catch proxies are in place.
