### ISSUE TITLE
Refactor logging output to be a valid JSON

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/golos#133]

**Comment by AKorpusenko** [comment]
Logs will be presented in such json format. Example:
```
{
  "context": {
    "level": "warn",
    "file": "some_file_with_logs.cpp",
    "line": 23,
    "method": "main",
    "hostname": "",
    "thread_name": "th_a",
    "timestamp": "YYYY-MM-DDTHH:MM:SS",
    "context": "default"
  },
  "format": "${answer}",
  "data": {
    "answer": 42
  }
}

```

**Comment by AKorpusenko** [comment]
A new version of logging output in json format will be optional. You can pass -DENABLE_JSON_LOGGING_OUTPUT to cmake to enable json logs. Otherwise there would be old logs.

**Comment by muhazzz** [comment]
Было бы прекрасно иметь следующее:
1. Оставить возможность читать текущий (не структурированный) вариант лога для целей отладки, запуска на сендбоксе и т.д.
2. ЭТОТ ЖЕ релиз, без всякой пересборки, должен уметь запускаться с переменной окружения JSON_LOG=true и тогда логи будут выводиться в структурированном виде. Можно и в config.ini этот же параметр продублировать, но для этого точно не нужна пересборка, т.к. один и тот же билд будет удобно как тестировать с обычным логом, так и эксплуатировать с машиночитаемым, структурированным.
3. Если есть возможность упростить JSON-лог, то нужно упрощать. Как минимум, избавиться от ненужных вложенностей типа "context" ("data" можно оставить), Например, вот так:
{
  "level": "warn",
  "file": "some_file_with_logs.cpp",
  "line": 23,
  "method": "main",
  "hostname": "",
  "thread_name": "th_a",
  "timestamp": "YYYY-MM-DDTHH:MM:SS",
  "context": "default",
  "format": "${answer}",
  "data": {
    "answer": 42
  }
}

**Comment by AKorpusenko** [comment]
In last commit to fc (look branch "133-refactor-logging-output") a json_console_appender was implemented. Next step is to figure out how to replace console_appender with json_console_appender.

**Comment by AKorpusenko** [comment]
Added JSON logging format exactly as @muhazzz asked (commit 79445919fd84af26ab0ab6f7eee14b7d434ffe12).
In process: adding an option to use json_console_appender instread of console_appender to enable json logs.

**Comment by AKorpusenko** [comment]
- In commit (e9a813ed2aa0f7624d61fa6c9d82637598e06392) and commit (48b9aa105a4340c31214af2fccd416616d23527a) to fc was implemented adding json_console_appender to configuration.
- In commit (15978cbb34e138d704f3b63bde05ff13313e6dc1) to golos, branch #133-refactor-loggin-output was implemented option to do logging in JSON format.
Commit changes: `load_logging_config_from_ini_file` is now searching for string `[log.json_console_appender.stderr]`, if it was found, then logs will be presented in JSON format.

You can switch usual logging format to JSON writing `[log.json_console_appender.stderr]` instead of `[log.console_appender.stderr]` to `config.ini` file.

**Comment by Nemo1369** [comment]
Reviewed and closed with 5c4aeca

**Comment by Nemo1369** [comment]
Not merged yet
