### ISSUE TITLE
Refactor statd data pushing implementation

### ISSUE THREAD

**Issue by kotbegemot** [GolosChain/golos#209]
1. The thread of support is removed.
2. The Queue of integration remove.
3. Client's initialization for statd transferred to the implementation of the plug-in.
4. The **cmake** clean from **libcds** submodule
5. The **libcds** submodule remove.

**Comment by AKorpusenko** [comment]
Refactored these things:
1) Removed libcds locating and linking cmake functions (helpers)
2) Removed some cmake constants for locating libcds from root CMakeLists.txt
3) Refactored stat_sender in blockchain_statistics plugin.
4) Refactored blockchain_statistics plugin cmake, but I didn't refactor the method of including headers. I guess there is no need to that before #195 issue.

Also it's need to change names of variables and names of config.ini params, because now there are like `"chain-stats-recipient-ip" `. Thats ok, but no so obvious as "statsd-endpoints" for instance.

**Comment by AKorpusenko** [comment]
So, I thought it is a good idea to rename the params to make them clearer. DId this.

Please, review the code.

**Comment by muhazzz** [comment]
I will be really happy to get theese stats:

1. Number of incoming rpc calls (counter)
2. Number of internal daemon errors: bad_alloc, etc (counter)
3. Time from incoming rpc call to its completion (time in ms)
4. Sync time: current time minus time of the last block (in seconds)

Is it possible to implement them as soon as possible (with next HF/SF)?
