### ISSUE TITLE
Increase STEEMIT_UPVOTE_LOCKOUT at HF17

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#454]
Because the payout time is fixed after HF17, it's possible that some people will upvote posts just before the payout time, which could be abusing. STEEMIT_UPVOTE_LOCKOUT is currently 1 minute, which means others have little chance to find that kind of abusing or downvote accordingly.

Here I propose we increase STEEMIT_UPVOTE_LOCKOUT to 12 hours or so, during that period people can still upvote and downvote, but only downvotes take effect, let the upvotes be no-op.

**Comment by VIM-Arcange** [comment]
IMHO, a one day upvote lockout is too long. 
Why not align with Steemit current value which is 12 hours?

**Comment by afalaleev** [comment]
@VIM-Arcange issue description is fixed. 
In the code there is already 12 hours: https://github.com/GolosChain/golos/commit/39da2496ac5949a9b263a9d09485c590ad321e4a#diff-95d4da2aa9bffe9044cd7d846ec6f435R269

**Comment by kotbegemot** [comment]
https://github.com/GolosChain/golos/pull/455

**Comment by primusd** [comment]
Please stop adding new features into Release Candidate branch.

**Comment by kotbegemot** [comment]
@VIM-Arcange @primusd  https://github.com/GolosChain/golos/issues/461

**Comment by VIM-Arcange** [comment]
Why for the sake of god are you opening so many issues for the same topic?

The main description of this issue mentioned a 1 day lockout and has been edited to replace it with "12 hours" later, This is bad practice and  doesn't help for discussion. How can one follow this with such a inconsistent management?

@primusd I think this should not be considered as a new feature has it is already implemented in the current HF. Raising the issue was a good idea.

Anyway, I agree that there should be a discussion with the community before changing it.
Moreover, this is likely the intention of @afalaleev as he wrote "Here I propose we increase STEEMIT_UPVOTE_LOCKOUT ..."

Shouldn't be a proposal be discussed before implementation?
To be honest, I have been surprised that my single comment was taken into consideration and implemented so fast.

**Comment by bitfag** [comment]
@VIM-Arcange there was actually another discussions regarding this in telegram chats. At first, @gropox pointed about steemit initiative to increase STEEMIT_UPVOTE_LOCKOUT while they switched to 7-day window, but then witnesses asked "why this change introduced **after** HF features agreement?", so core finally removed it.
