### ISSUE TITLE
get_discussions_by_... issues

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos#648]
Steps to reproduce:

**Setup**
On fresh testnet:
1. `post_comment alice test "" ptest "Test post!" "<h1>title!</h1><p>hello!</p><hr>test..." "{}" true`
2. `post_comment bob test "" ptest "Bob's test post!" "<h1>title!</h1><p>hello!</p><hr>test..." "{\"tags\":[\"tag1\",\"tag2\"]}" true`

**Issues**
1. `get_discussions_by_comments` fails with error if post have no comments
    * api: `get_discussions_by_comments {"select_authors":["bob"],"limit":10}`
    * **Expected result**: empty array or array with bob's post
    * **Actual result**: `"Assert Exception (10) !!query.start_author: Must get comments for a specific author"`

2. `get_discussions_by_...` methods skips posts without tags
    * call api: `get_discussions_by_created {"select_authors":["alice"],"limit":10}`
    * call api: `get_discussions_by_created {"select_authors":["bob"],"limit":10}`
    * **Expected result**: each call returns `discussion` object
    * **Actual result**: 1st api call returns empty array

The same result when calling other `get_discussions_by_...` methods

**Comment by afalaleev** [comment]
1. `get_discussions_by_comments()` works by other steps than other `get_discussions_by_` . It requires the field `start_author`, the author of comments. And it returns a list of comments, not list of posts. All other fields in a `query` are used to filter by post, for which comment was posted.
1. I confirm, this is the bug. The fix is to add the empty tag for posts without tags.
